version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - .:/var/www/html/
        links:
            - composer
        networks:
            - default
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: td1gestion
            MYSQL_USER: rootuser
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: rootuser
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
    composer:
        image: composer
        links:
            - db:db
        working_dir: /var/www/html/ 
        volumes:
            - .:/var/www/html/
        entrypoint: /bin/bash -c "if [ ! -d vendor ]; then composer install; fi"
volumes:
    persistent:

