version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - .:/var/www/html/
        links:
            - composer
            - db
    db:
        image: mysql
        volumes:
            - ./script:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: td1gestion
            MYSQL_USER: rootuser
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        links:
            - db
    composer:
        image: composer
        links:
            - db
        working_dir: /var/www/html/ 
        volumes:
            - .:/var/www/html/
        entrypoint: /bin/bash -c "if [ ! -d vendor ]; then composer install; fi"
volumes:
    persistent:

